[package]
name = "kernel-model-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
derive = { path = "derive", optional = true }

[dev-dependencies]
rand = "0.8.5"

[features]
default = ["derive"]
derive = ["dep:derive"]

[workspace]
members = ["derive"]