[package]
name = "km-checker"
version = "0.1.0"
edition = "2021"

[dependencies]
km-derive = { path = "derive", optional = true }

[features]
default = ["derive"]
derive = ["dep:km-derive"]

[workspace]
members = ["derive"]